export const productKeys = {
  all: ['products'],
  lists: () => [...productKeys.all, 'list'],
  list: (filters) => [...productKeys.lists(), filters],
  details: () => [...productKeys.all, 'detail'],
  detail: (slug) => [...productKeys.details(), slug],
  detailedById: (id) => [...productKeys.all, 'detailed', id],
  byCategory: (slug, params = {}) => [...productKeys.all, 'category', slug, params],
  byTag: (tag, params = {}) => [...productKeys.all, 'tag', tag, params],
  related: (slug, categorySlug = '') => [...productKeys.all, 'related', slug, categorySlug || ''],
  search: (q, params = {}) => [...productKeys.all, 'search', String(q || '').trim().toLowerCase(), params],
  bestsellers: () => [...productKeys.all, 'bestsellers'],
  featured: () => [...productKeys.all, 'featured'],
  newArrivals: () => [...productKeys.all, 'newArrivals'],
  beauty: () => [...productKeys.all, 'beauty'],
}
