export const adminKeys = {
  all: ['admin'],
  me: () => [...adminKeys.all, 'me'],
  checkoutSettings: () => [...adminKeys.all, 'checkout-settings'],
  shippingSettings: () => [...adminKeys.all, 'shipping-settings'],
  dashboardSummary: () => [...adminKeys.all, 'dashboard-summary'],
  ordersSummary: () => [...adminKeys.all, 'orders-summary'],
  ordersList: (bucket, page, search) => [...adminKeys.all, 'orders-list', bucket, page, search || ''],
  orderDetail: (orderId) => [...adminKeys.all, 'order', String(orderId || '')],
  orderTracking: (orderId) => [...adminKeys.all, 'order-tracking', String(orderId || '')],
  productsAll: (page, search) => [...adminKeys.all, 'products-all', page, search || ''],
  productsActive: () => [...adminKeys.all, 'products-active'],
  productsLowStock: () => [...adminKeys.all, 'products-low-stock'],
  productsArchived: (page) => [...adminKeys.all, 'products-archived', page],
  users: (page, search, role) => [...adminKeys.all, 'users', page, search || '', role || ''],
  userDetail: (userId) => [...adminKeys.all, 'user', String(userId || '')],
  carts: (variant, page) => [...adminKeys.all, 'carts', variant, page],
  wishlists: (variant, page) => [...adminKeys.all, 'wishlists', variant, page],
  wishlistsPopular: () => [...adminKeys.all, 'wishlists-popular'],
  coupons: (page, status, search) => [...adminKeys.all, 'coupons', page, status, search || ''],
  staff: (page, search) => [...adminKeys.all, 'staff', page, search || ''],
  staffProfile: () => [...adminKeys.all, 'staff-profile'],
  returns: (page, status) => [...adminKeys.all, 'returns', page, status || ''],
  returnDetail: (orderId) => [...adminKeys.all, 'return', String(orderId || '')],
  rtoOrders: (page) => [...adminKeys.all, 'rto-orders', page],
  rtoAnalytics: () => [...adminKeys.all, 'rto-analytics'],
  oosInquiries: (page, status, search) => [...adminKeys.all, 'oos', page, status, search || ''],
}
